source 'https://rubygems.org'
ruby '2.4.0'

gem 'dotenv-rails', '>= 2.7.0', :require => 'dotenv/rails-now'
gem 'rb-readline'
gem 'oj'
gem 'rails', '6.0.3.5'
gem 'pg'
gem 'sassc-rails', '>= 1.3.0'
gem 'uglifier'
gem 'jquery-rails', '>= 4.3.1'
gem 'octokit'
gem 'bootstrap-sass'
gem 'will_paginate-bootstrap'
gem 'elasticsearch', '~> 2'
gem 'elasticsearch-model', git: 'https://github.com/elasticsearch/elasticsearch-rails'
gem 'elasticsearch-rails', git: 'https://github.com/elasticsearch/elasticsearch-rails'
gem 'nokogiri'
gem 'typhoeus'
gem 'redis'
gem 'hiredis'
gem 'rack-canonical-host'
gem 'sitemap_generator'
gem 'spdx'
gem 'sanitize-url'
gem 'semantic'
gem 'simple-rss'
gem 'faraday-http-cache'
gem 'fog-aws'
gem 'omniauth-github'
gem 'dalli'
gem 'counter_culture', '>= 1.5.0'
gem 'simple_form', '>= 4.0.0'
gem 'sidekiq'
gem 'sidekiq-unique-jobs', git: 'https://github.com/mhenrixon/sidekiq-unique-jobs'
gem 'font-awesome-rails', '>= 4.7.0.5'
gem 'mime-types', require: 'mime/types/columnar'
gem 'fast_blank'
gem 'fast_xs'
gem 'fast_xor'
gem 'premailer-rails', '>= 1.10.3'
gem 'gemoji'
gem 'js_cookie_rails', '>= 2.1.3'
gem 'postgres_ext', git: 'https://github.com/gocardless/postgres_ext', branch: 'rails-5'
gem 'foreman', require: false
gem 'puma'
gem 'payola-payments', git: 'https://github.com/librariesio/payola'
gem 'rack-timeout'
gem 'semantic_range'
gem 'license-compatibility'
gem 'escape_utils'
gem 'mail', require: ['mail', 'mail/utilities', 'mail/parsers']
gem 'pictogram', '>= 2.0.8'
gem 'rails-timeago', git: 'https://github.com/librariesio/rails-timeago'
gem 'rack-attack'
gem 'rack-attack-rate-limit', require: 'rack/attack/rate-limit'
gem 'api-pagination'
gem 'indefinite_article'
gem 'faraday_middleware'
gem 'parallel', require: nil
gem 'highscore'
gem 'fast-stemmer'
gem 'bloomfilter-rb'
gem 'omniauth-gitlab'
gem 'omniauth-bitbucket'
gem 'chartkick'
gem 'groupdate'
gem 'turbolinks'
gem 'gitlab', git: 'https://github.com/librariesio/gitlab'
gem 'bitbucket_rest_api', git: 'https://github.com/librariesio/bitbucket'
gem 'github-markup', require: 'github/markup'
gem 'commonmarker'
gem 'RedCloth'
gem 'rdoc'
gem 'asciidoctor'
gem 'org-ruby'
gem 'creole'
gem 'bundler'
gem 'bibliothecary'
gem 'stripe'
gem 'github-linguist'
gem 'appsignal'
gem 'rack-cors', :require => 'rack/cors'
gem 'active_model_serializers', '>= 0.10.10'

group :development do
  gem 'spring'
  gem 'sql_queries_count', '>= 0.0.1'
  gem 'brakeman', :require => false
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-maintenance', require: nil
  gem 'capistrano-rails-console', require: nil
  gem 'listen'
  gem 'spring-watcher-listen'
end

group :development, :test do
  gem 'rspec-rails', '>= 3.5.2'
end

group :test do
  gem 'factory_girl_rails', '>= 4.8.0'
  gem 'database_cleaner'
  gem 'rspec_junit_formatter'
  gem 'shoulda'
  gem 'simplecov', require: false
  gem 'codeclimate-test-reporter', require: false
  gem 'faker'
  gem 'poltergeist'
  gem 'json_spec'
  gem 'rspec-sidekiq'
end

group :production do
  gem 'bugsnag'
  gem 'lograge', '>= 0.9.0'
  gem 'rails_safe_tasks'
end
